version: "3.7"

services:
  ebus-client:
    image: ebus-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/local/src
    working_dir: /usr/local/src
    ports:
      - 3202:3000
    command: npm run start

  db:
    image: postgis/postgis:13-3.1
    expose:
      - "5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 3
  web:
    build: .
    volumes:
      - .:/usr/src
      - ./frontend/build:/usr/src/static/
    ports:
      - "9202:9202"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
  
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - '4000:4000'
    command: yarn dev
  dynamodb:
    container_name: dynamodb_local
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
volumes:
  dynamodata: {}