# Generated by Django 3.2.12 on 2022-04-18 14:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('route_id', models.CharField(max_length=50)),
                ('route_short_name', models.CharField(blank=True, max_length=50)),
                ('route_long_name', models.CharField(blank=True, max_length=100)),
                ('route_desc', models.CharField(max_length=500)),
                ('route_type', models.CharField(choices=[('0', 'Tram, Streetcar, Light rail'), ('1', 'Subway, Metro'), ('2', 'Rail'), ('3', 'Bus'), ('4', 'Ferry'), ('5', 'Cable Car'), ('6', 'Gondola'), ('7', 'Funicular')], max_length=50)),
                ('route_url', models.CharField(blank=True, max_length=100)),
                ('route_color', models.CharField(blank=True, max_length=50)),
                ('route_text_color', models.CharField(blank=True, max_length=50)),
                ('route_sort_order', models.CharField(blank=True, max_length=50)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('route_distance', models.FloatField(blank=True, null=True)),
                ('trips_monday', models.IntegerField(blank=True)),
                ('trips_tuesday', models.IntegerField(blank=True)),
                ('trips_wednesday', models.IntegerField(blank=True)),
                ('trips_thursday', models.IntegerField(blank=True)),
                ('trips_friday', models.IntegerField(blank=True)),
                ('trips_saturday', models.IntegerField(blank=True)),
                ('trips_sunday', models.IntegerField(blank=True)),
                ('zev_charging_infrastrucutre', models.BooleanField(default=False)),
                ('zev_notes', models.TextField(blank=True, null=True)),
                ('pct_zev_service', models.FloatField(blank=True, null=True)),
                ('num_zev', models.IntegerField(blank=True, null=True)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.agency')),
            ],
        ),
    ]
