# Generated by Django 3.2.12 on 2022-04-18 18:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='accepted_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
