# Generated by Django 3.2.13 on 2022-05-04 20:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_auto_20220427_1553'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='route',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='zev_charging_infrastrucutre',
            new_name='zev_charging_infrastructure',
        ),
    ]
