# Generated by Django 3.2.13 on 2022-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_auto_20220504_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_desc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
