#!/bin/bash

set -e

if [[ -n "${EBUSTRANSIT_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") Run a Django management command
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else 
        docker compose \
            --env-file .env \
            run --rm --entrypoint python \
            web \
            manage.py "$@"
    fi
fi