#!/bin/bash

set -e

if [[ -n "${EBUSTRANSIT_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run linters and tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Running tests..."
        docker-compose up -d
        docker-compose exec web python manage.py test
    fi
fi