#!/bin/bash

set -e

if [[ -n "${EBUSTRANSIT_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images and execute database migrations.
"
}

function cleanup() {
    docker-compose stop
}

trap cleanup ERR

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # set permissions on volumes files to user
        sudo chown -R $(id -u $USER):$(id -u $USER) ./data/db
        
        # Ensure container images are current
        docker-compose build

        # Bring up PostgreSQL and Django
        docker-compose up -d

        # Apply any outstanding Django migrations
        docker-compose exec web python manage.py migrate

        # Collect Django static files
        docker-compose exec web python manage.py collectstatic --no-input

        #gather & load a sample gtfs file for testing purposes 
        docker-compose exec web python manage.py loadfeeds --sample
        
        docker-compose down
    fi
fi